### ISSUE TITLE
Script param explanation

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orautils#4]
Hello sir, can you please explain what the parameter to the stopWeblogicAdmin.sh script is supposed to be:

https://github.com/biemond/biemond-orautils/blob/master/templates/stopWeblogicAdmin.sh.erb#L34-L35

```
# pwd
/opt/scripts/wls
# ./showStatus.sh 
 __________________________________
|              NAME|  STATUS|   PID|
|__________________|________|______|
|             admin|  Online|  9196|
|__________________|________|______|
|       NodeManager|     ---|   ---|
|__________________|________|______|
# ./stopWeblogicAdmin.sh 
Stopping Weblogic admin for domain ADAMTEST....
Checking if Weblogic admin for domain ADAMTEST is up....
CONFIG_JVM_ARGS -Dweblogic.ssl.JSSEEnabled=false -Dweblogic.security.SSL.enableJSSE=false 
The Weblogic admin for domain ADAMTEST is NOT running....
Done....
# ./stopWeblogicAdmin.sh admin
Stopping Weblogic admin for domain ADAMTEST....
Checking if Weblogic admin for domain ADAMTEST is up....
CONFIG_JVM_ARGS -Dweblogic.ssl.JSSEEnabled=false -Dweblogic.security.SSL.enableJSSE=false 
The Weblogic admin for domain ADAMTEST is NOT running....
Done....
```

**Comment by biemond** [comment]
it is the domain part bug again plus for this your nodemanager should be running.

Very strange that the nodemanager does not show up with showStatus.sh

**Comment by adamjk-dev** [comment]
Oh, I killed it previously, perhaps that is the issue. But, I ran startNodeManager.sh it failed, so I stopped there.

```
# ./startNodeManager.sh 
Starting the Weblogic NodeManager....
Checking if the Weblogic NodeManager is already started....
The NodeManager is not running yet.. Starting NodeManager now....
+ CLASSPATH=/opt/java/jdk1.7.0_67/lib/tools.jar:/app/oracle/wls1212/wlserver/server/lib/weblogic_sp.jar:/app/oracle/wls1212/wlserver/server/lib/weblogic.jar:/app/oracle/wls1212/wlserver/server/lib/webservices.jar:/app/oracle/wls1212/wlserver/../oracle_common/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/app/oracle/wls1212/wlserver/../oracle_common/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/app/oracle/wls1212/wlserver/modules/features/oracle.wls.common.nodemanager_1.0.0.0.jar::/app/oracle/wls1212/wlserver/..
+ '[' '!' -z '' ']'
+ '[' '!' -z '' ']'
+ export CLASSPATH
+ export PATH
+ cd /app/oracle/wls1212/wlserver/../oracle_common/common/nodemanager
+ set -x
+ '[' '' '!=' '' ']'
+ '[' '' '!=' '' ']'
+ /opt/java/jdk1.7.0_67/bin/java -client -Xms32m -Xmx200m -XX:MaxPermSize=128m -Dcoherence.home=/app/oracle/wls1212/wlserver/../coherence -Dbea.home=/app/oracle/wls1212/wlserver/.. -Dweblogic.ssl.JSSEEnabled=false -Dweblogic.security.SSL.enableJSSE=false -Xverify:none -Djava.endorsed.dirs=/opt/java/jdk1.7.0_67/jre/lib/endorsed:/app/oracle/wls1212/wlserver/../oracle_common/modules/endorsed -Djava.security.policy=/app/oracle/wls1212/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/opt/java/jdk1.7.0_67 weblogic.NodeManager -v
<Apr 28, 2015 8:36:03 AM PDT> <INFO> <Loading domains file: /app/oracle/wls1212/oracle_common/common/nodemanager/nodemanager.domains>
<Apr 28, 2015 8:36:03 AM PDT> <WARNING> <Domains file not found: /app/oracle/wls1212/oracle_common/common/nodemanager/nodemanager.domains>
<Apr 28, 2015 8:36:04 AM PDT> <INFO> <Loading identity key store: FileName=/app/oracle/wls1212/oracle_common/common/nodemanager/security/DemoIdentity.jks, Type=jks, PassPhraseUsed=true>
<Apr 28, 2015 8:36:04 AM PDT> <SEVERE> <Fatal error in NodeManager server>
weblogic.nodemanager.common.ConfigException: Identity key store file not found: /app/oracle/wls1212/oracle_common/common/nodemanager/security/DemoIdentity.jks
	at weblogic.nodemanager.server.SSLConfig.loadKeyStoreConfig(SSLConfig.java:170)
	at weblogic.nodemanager.server.SSLConfig.access$000(SSLConfig.java:32)
	at weblogic.nodemanager.server.SSLConfig$1.run(SSLConfig.java:111)
	at java.security.AccessController.doPrivileged(Native Method)
	at weblogic.nodemanager.server.SSLConfig.<init>(SSLConfig.java:108)
	at weblogic.nodemanager.server.NMServer.<init>(NMServer.java:121)
	at weblogic.nodemanager.server.NMServer.main(NMServer.java:383)
	at weblogic.NodeManager.main(NodeManager.java:31)
```

**Comment by biemond** [comment]
all the scripts don't use any parameters, they are set by the init.pp and use the defaults of params.pp manifest

Now you need to set all the right params like  nodemanager home path . In 12c the nodemanager is part of the domain

orautils::osOracleHomeParam:      *wls_oracle_base_home_dir
orautils::oraInventoryParam:      "/opt/oracle/oraInventory"
orautils::osDomainTypeParam:      "admin"
orautils::osLogFolderParam:       *wls_log_dir
orautils::osDownloadFolderParam:  *wls_download_dir
orautils::osMdwHomeParam:         *wls_middleware_home_dir
orautils::osWlHomeParam:          *wls_weblogic_home_dir
orautils::oraUserParam:           *wls_os_user

orautils::nodeMgrPortParam:       5556

orautils::wlsUserParam:           *wls_weblogic_user
orautils::jsseEnabledParam:       true
orautils::osDomainParam:          *domain_name
orautils::osDomainPathParam:      "/opt/oracle/wlsdomains/domains/Wls1213"
orautils::nodeMgrPathParam:       "/opt/oracle/wlsdomains/domains/Wls1213/bin"
orautils::nodeMgrAddressParam:    *domain_adminserver_address
orautils::wlsPasswordParam:       *domain_wls_password
orautils::wlsAdminServerParam:    *domain_adminserver
orautils::customTrust:             true
orautils::trustKeystoreFile:       '/vagrant/truststore.jks'
orautils::trustKeystorePassphrase: 'welcome'

**Comment by adamjk-dev** [comment]
I think we are setting everything that we can or found appropriate:

```
class { 'orautils':
    osOracleHomeParam       => $oracle_home_dir,
    oraInventoryParam       => $oracle_inventory_dir,
    osDomainTypeParam       => 'admin',
    osLogFolderParam        => $weblogic_log_dir,
    osDownloadFolderParam   => $download_dir,
    osMdwHomeParam          => $middleware_home_dir,
    osWlHomeParam           => $weblogic_home_dir,
    oraUserParam            => $wls_os_user,
    oraGroupParam           => $wls_os_group,
    osDomainParam           => $domain_name,
    osDomainPathParam       => $domains_path,
    nodeMgrPathParam        => "${$weblogic_home_dir}/server/bin",
    nodeMgrPortParam        => $nodemanager_port,
    nodeMgrAddressParam     => $nodemanager_address,
    wlsUserParam            => $wls_os_user,
    wlsPasswordParam        => $wls_user_password,
    wlsAdminServerParam     => 'AdminServer',
    jsseEnabledParam        => false,
    customTrust             => false,
    trustKeystoreFile       => undef,
    trustKeystorePassphrase => undef,
  }

# Create the autostart stuff for WL
  orautils::nodemanagerautostart { 'autostart_weblogic':
    version                 => $wl_version,
    wlHome                  => $weblogic_home_dir,
    user                    => $wls_os_user,
    domain                  => $domain_name,
    domainPath              => "${domains_path}/${domain_name}",
    logDir                  => undef,
    jsseEnabled             => false,
    customTrust             => false,
    trustKeystoreFile       => undef,
    trustKeystorePassphrase => undef,
  }
```

**Comment by biemond** [comment]
this is not correct ( also ${$ )
nodeMgrPathParam        => "${$weblogic_home_dir}/server/bin",

should be your domain name for wls 12.1.2
nodeMgrPathParam =>  "/opt/oracle/wlsdomains/domains/Wls1213/bin"

**Comment by adamjk-dev** [comment]
Hrm, what files are in that bin directory, so I can find it for where we configure it? 

I have it currently set to:
```
# ll /app/oracle/wls1212/wlserver/server/bin/
total 16
drwxr-x--- 2 ser_dvapp mqm 4096 Apr 28 08:49 international
-rwxr-x--- 1 ser_dvapp mqm 3980 Apr 28 08:50 setWLSEnv.sh
-rwxr-x--- 1 ser_dvapp mqm 4727 Apr 28 08:50 startNodeManager.sh
```

We put things in /projects/<domain name>:
```
# ls /projects/
ADAMTEST
# ls /projects/ADAMTEST/
autodeploy  bin  common  config  console-ext  derby.log  derbyShutdown.log  edit.lok  fileRealm.properties  init-info  lib  logs  nodemanager  pending  security  servers  shutdown.py  startWebLogic.sh  tmp
```

**Comment by adamjk-dev** [comment]
Yeah, when I updated the parameter to orautils I was able to stop and start the node manager from the scripts in /opt/scripts/wls, so you were correct.

For me:
```
class { 'orautils':
  ... 
  nodeMgrPathParam        => "${domains_path}/${domain_name}/bin",
  ...
}
```
